import AppKit

/// The last N things you copied, searchable and re-copyable.
///
/// This cannot live in Lua, for two independent reasons. `NSPasteboard` has no change
/// notification at all — `changeCount` has to be polled on a timer, and a provider
/// only runs while its submenu is open. And a provider is re-loaded into a throwaway
/// state on every keystroke with no `io`, so it is stateless by construction; only the
/// host can remember anything between activations, exactly as `UsageStore` argues.
///
/// **Off by default.** A launcher that starts recording everything you copy without
/// being asked is not a good default, and neither is one that writes it to disk.
@MainActor
final class ClipboardHistory {
    struct Entry: Codable, Equatable {
        var text: String
        var captured: Date
    }

    /// What one look at the pasteboard found. Injected so tests can drive the whole
    /// state machine without touching the real pasteboard — the same reason
    /// `UsageStore` takes a `url` it can be handed `nil` for.
    struct Reading {
        var changeCount: Int
        /// Set by password managers and the like. Such an entry is never recorded.
        var concealed: Bool
        var string: String?
    }

    private(set) var entries: [Entry] = []
    private var spec = ClipboardSpec()
    private var timer: DispatchSourceTimer?
    private var lastChangeCount: Int
    private let url: URL?
    private let read: @MainActor () -> Reading
    private var flushScheduled = false

    /// Pasteboard types that mean "this was not copied by a person for later use".
    /// The convention is org.nspasteboard.org's; honouring it is what keeps a password
    /// manager's clipboard out of the history.
    static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    static var defaultURL: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Library/Application Support")
        return base.appendingPathComponent("Kitsune/clipboard.json")
    }

    /// `nil` for `url` keeps the history in memory whatever `persist` says. Tests
    /// construct it that way so a run can never read — or write — real clipboard data.
    init(url: URL?, read: @escaping @MainActor () -> Reading = ClipboardHistory.readGeneralPasteboard) {
        self.url = url
        self.read = read
        lastChangeCount = read().changeCount
        load()
    }

    static func readGeneralPasteboard() -> Reading {
        let pasteboard = NSPasteboard.general
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        return Reading(changeCount: pasteboard.changeCount,
                       concealed: !types.isDisjoint(with: concealedTypes),
                       string: pasteboard.string(forType: .string))
    }

    // MARK: - Lifecycle

    /// Republished on every config reload. Switching the feature off stops the timer,
    /// drops everything already captured and deletes any file: "nothing is recorded
    /// while it is off" is a stronger claim than "the timer stopped".
    func apply(_ next: ClipboardSpec) {
        guard next != spec else { return }
        let wasEnabled = spec.enabled
        spec = next
        guard next.enabled else {
            stop()
            entries = []
            removeFile()
            return
        }
        trim()
        // Persistence is opt-in, so revoking it has to take the file with it.
        if !next.persist { removeFile() } else { scheduleFlush() }
        if !wasEnabled {
            // Whatever is on the pasteboard right now was copied before the user asked
            // for any of this to be recorded.
            lastChangeCount = read().changeCount
        }
        start()
    }

    private func start() {
        stop()
        let timer = DispatchSource.makeTimerSource(queue: .main)
        let interval = max(0.1, spec.pollInterval)
        timer.schedule(deadline: .now() + interval, repeating: interval)
        timer.setEventHandler { [weak self] in MainActor.assumeIsolated { self?.poll() } }
        timer.resume()
        self.timer = timer
    }

    private func stop() {
        timer?.cancel()
        timer = nil
    }

    /// Called after the launcher itself writes to the pasteboard, so re-copying an
    /// entry does not read its own write back in a moment later.
    func noteOwnWrite() { lastChangeCount = read().changeCount }

    // MARK: - Capture

    func poll() {
        guard spec.enabled else { return }
        let reading = read()
        guard reading.changeCount != lastChangeCount else { return }
        // Recorded whatever happens next, so a skipped entry is not re-examined on
        // every tick until something else is copied.
        lastChangeCount = reading.changeCount
        guard !reading.concealed, let text = reading.string, !text.isBlank else { return }
        record(text)
    }

    private func record(_ text: String, now: Date = Date()) {
        // A repeat copy moves the existing entry to the front rather than duplicating
        // it: the list is a history of what you have, not of what you did.
        entries.removeAll { $0.text == text }
        entries.insert(Entry(text: text, captured: now), at: 0)
        trim()
        scheduleFlush()
    }

    private func trim() {
        let limit = max(1, spec.limit)
        if entries.count > limit { entries = Array(entries.prefix(limit)) }
    }

    func clear() {
        entries = []
        removeFile()
    }

    // MARK: - Rows

    /// Newest first, fuzzy-filtered. Rows carry a `RowAction`, so Return copies the
    /// entry back and dismisses through the same path a row action takes — there is no
    /// second dispatch route to keep in step.
    func results(for query: String, limit: Int) -> [DisplayRow] {
        let matched: [(offset: Int, entry: Entry, score: Int)] = entries.enumerated().compactMap { index, entry in
            guard !query.isEmpty else { return (index, entry, index) }
            guard let score = FuzzyMatcher.score(query, in: entry.text) else { return nil }
            return (index, entry, score)
        }
        // Recency breaks a score tie, which is what keeps the newest of two equally
        // good matches on top.
        return matched.sorted { $0.score == $1.score ? $0.offset < $1.offset : $0.score < $1.score }
            .prefix(max(0, limit))
            .map { match in
                DisplayRow(id: "clip:\(match.offset)", kind: .action, label: Self.label(for: match.entry.text),
                           detail: Self.detail(for: match.entry.text), symbol: "doc.on.clipboard",
                           image: nil, score: match.score, section: "clipboard",
                           rowAction: .copyText(match.entry.text))
            }
    }

    /// One line, whitespace collapsed. A row is 44 points tall and a copied paragraph
    /// is not, so the label is the shape of the row rather than of the entry.
    static func label(for text: String) -> String {
        let flattened = text.split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .joined(separator: " ")
        return flattened.count > 120 ? String(flattened.prefix(120)) + "…" : flattened
    }

    static func detail(for text: String) -> String {
        let lines = text.split(whereSeparator: \.isNewline).count
        let characters = text.count
        let plural = characters == 1 ? "" : "s"
        return lines > 1 ? "\(lines) lines · \(characters) characters" : "\(characters) character\(plural)"
    }

    // MARK: - Persistence

    private func load() {
        guard let url, let data = try? Data(contentsOf: url) else { return }
        entries = (try? JSONDecoder().decode([Entry].self, from: data)) ?? []
    }

    /// Coalesced like `UsageStore`'s: capture happens on a timer while the user is
    /// working, and touching the disk on every copy would be a tax on nothing.
    private func scheduleFlush() {
        guard url != nil, spec.persist, !flushScheduled else { return }
        flushScheduled = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) { [weak self] in
            guard let self else { return }
            flushScheduled = false
            flush()
        }
    }

    private func flush() {
        guard let url, spec.persist, let data = try? JSONEncoder().encode(entries) else { return }
        DispatchQueue.global(qos: .utility).async {
            try? FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try? data.write(to: url, options: .atomic)
        }
    }

    private func removeFile() {
        guard let url else { return }
        try? FileManager.default.removeItem(at: url)
    }
}
